//
// Created by edge7 on 14/03/23.
//

#ifndef ESP32_PERSON_DETECTION_WIFI_UTILITY_H
#define ESP32_PERSON_DETECTION_WIFI_UTILITY_H
void wifi_init_sta();

#endif //ESP32_PERSON_DETECTION_WIFI_UTILITY_H
